language: python
sudo: false
dist: bionic
matrix:
  fast_finish: true
  include:
      - python: "3.6"
        env: TOXENV=py36
      - python: "3.7"
        env: TOXENV=py37
      - python: "3.8"
        env: TOXENV=py38,py38-lint
install:
  - pip install tox
script:
  - tox
after_success:
  - pip install coveralls
  - coveralls
cache:
  pip: true
  directories:
    - eggs/
